# Generated by Django 3.2.8 on 2021-10-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Balance',
            field=models.DecimalField(decimal_places=16, max_digits=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Amount',
            field=models.DecimalField(decimal_places=16, max_digits=30),
        ),
    ]
