# Generated by Django 3.2.8 on 2022-04-08 08:12

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_analytics', '0002_auto_20211008_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='RoundTime',
            field=models.IntegerField(default=time.time),
        ),
    ]
