# Generated by Django 3.2.8 on 2022-04-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_analytics', '0005_auto_20220412_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='TransactionID',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
